theme: jekyll-theme-cayman
repository: prashanthgl/prashanthgl.github.io
show_downloads: false
title: Follow the Sun
description: An Overview of the follow the sun methodology in software development.
